server {
    listen 80;
    server_name messages.blackbookproperties.com;
    root /usr/share/nginx/html;
    index index.html;

    location = / {
        try_files /index.html =404;
    }
    location = /terms {
        try_files /terms.html =404;
    }
    location = /privacy {
        try_files /privacy.html =404;
    }
    # Alias adicional por si RingCentral usa /privacy-policy
    location = /privacy-policy {
        try_files /privacy.html =404;
    }
    location / {
        try_files $uri $uri.html $uri/ =404;
    }
}
